name: freqinv
channels:
        - conda-forge
        - defaults
dependencies:
        - python>=3.7
        - ipython
        - cartopy
        - pip:
          - scipy
          - pandas
          - matplotlib
          - numpy
          - Cython

